In [122]:
# Goal : Cleaning the dataset and return a final clean dataset.
import pandas as pd

In [98]:
df = pd.read_csv("financial_transaction_test.csv")
df

                                      Transaction_Text       Label
0    IKEA furniture shopping | Ref:37c9a05e | Amoun...    Shopping
1    MakeMyTrip hotel booking | Ref:7fb0c9d1 | Amou...      Travel
2    Uber ride payment | Ref:f3653a0a | Amount: INR...      Travel
3    Flipkart electronics purchase | Ref:ab027ce0 |...    Shopping
4    HDFC home loan EMI | Ref:44608adc | Amount: IN...         EMI
..                                                 ...         ...
995  Myntra clothing order | Ref:45daca7d | Amount:...    Shopping
996  SBI car loan EMI | Ref:613c7ae6 | Amount: INR ...         EMI
997  Ola cab fare | Ref:871b709f | Amount: INR 3451...      Travel
998  Zomato dinner bill | Ref:6fb63408 | Amount: IN...        Food
999  Zerodha stock purchase | Ref:0c980941 | Amount...  Investment

[1000 rows x 2 columns]

In [118]:
df["Transaction_Text"][1]

'MakeMyTrip hotel booking | Ref:7fb0c9d1 | Amount: INR 11671.89'

In [100]:
df.loc[0, "Transaction_Text"]

'IKEA furniture shopping | Ref:37c9a05e | Amount: INR 3436.58'

In [114]:
price_list = []
for i in range(0, 999 + 1):
    k = (df["Transaction_Text"].str.split(r'^[^|]*\|[^|]*\|\s* Amount: INR'))[i][1].replace(" ", "")
    price_list.append(float(k))

In [116]:
r = {
    "Categories": df["Label"],
    "Amount spent": price_list
}

In [117]:
f = pd.DataFrame(r)
f

     Categories  Amount spent
0      Shopping       3436.58
1        Travel      11671.89
2        Travel      36513.25
3      Shopping      24844.16
4           EMI      15811.51
..          ...           ...
995    Shopping      34447.35
996         EMI       6484.62
997      Travel      34519.58
998        Food      20946.16
999  Investment       6493.65

[1000 rows x 2 columns]

In [123]:
f.to_csv("cleaned_dataset.csv", index=False)